name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: ./project
        file: ./project/Dockerfile
        push: true
        tags: rezwr01/project-server:latest
        build-args: |
          PYTHON_VERSION=3.11.4
        cache-from: type=registry,ref=rezwr01/project-server:buildcache
        cache-to: type=registry,ref=rezwr01/project-server:buildcache,mode=max

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: ./project
        file: ./project/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/rag-server:latest
        build-args: |
          PYTHON_VERSION=3.11.4
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rag-server:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rag-server:buildcache,mode=max

    - name: Set up environment variables
      run: |
        echo "NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }}" >> $GITHUB_ENV
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV

    - name: Run build
      run: |
        docker build -t rezwr01/project-server ./project
        docker run -e NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }} \
                   -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
                   rezwr01/project-server:latest