name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./project/Dockerfile
        push: true
        tags: rezwr01/project-server:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/rifatrzn/rag-server:latest

    - name: Set up environment variables
      run: |
        echo "NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }}" >> $GITHUB_ENV
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV

    - name: Run build
      run: |
        docker build -t rezwr01/project-server .
        docker run -e NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }} \
                   -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
                   rezwr01/project-server:latest
